server:
  port: 8072
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: config_server
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `key`, `value` from properties where application=? and profile=? and label=?
  datasource:
    #name: test
    url: jdbc:mysql://200.200.3.38:3306/wt_config
    username: root
    #使用远程的配置中心的参数
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20