eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    healthCheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
spring:
  application:
    name: gateway
server:
  port: 8084
feign:
   hystrix:
     enabled: true
hystrix:
   command:
     default:
       execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 5000
zuul:
  #ignored-services: microservice-provider-system          # 需要忽视的服务(配置后将不会被路由)
  routes:
    service1:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /sys/**                                        # 想要映射到的路径
      service-id: service-sys    # Eureka中的serviceId
    service2:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /pb/**                                   # 想要映射到的路径
      service-id: service-pb    # Eureka中的serviceId
    service3:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
        path: /file/**                                   # 想要映射到的路径
        service-id: service-file    # Eureka中的serviceId
    service4:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /oa/**                                   # 想要映射到的路径
      service-id: service-oa    # Eureka中的serviceId
redis:
   hostName: 200.200.3.38
   port: 6379
   timeout: 30
   maxIdle : 300
   maxTotal: 1000
   maxWaitMillis: 1000
   minEvictableIdleTimeMillis : 300000
   numTestsPerEvictionRun : 1024
   timeBetweenEvictionRunsMillis : 30000
   testOnBorrow : true
   testWhileIdle : true